# Project: fm
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = win/misc.o win/drv_linux.o win/eos.o win/fm.o win/font.o win/init.o win/io.o win/main.o win/match.o win/matchday.o win/menu.o $(RES)
LINKOBJ  = win/misc.o win/drv_linux.o win/eos.o win/fm.o win/font.o win/init.o win/io.o win/main.o win/match.o win/matchday.o win/menu.o $(RES)
LIBS =  -L"C:/GP2XSDK/lib" -lmingw32 -liconv -lgp2x -lSDL_image -lSDL_mixer -lSDL_ttf -lSDL_inifile -lSDLmain -lSDL -lpng -ljpeg -lvorbisidec -lmad -lfreetype -lz -lunicodefont   
INCS =  -I"C:/GP2XSDK/include/GP2X"  -I"C:/GP2XSDK/include/SDL"  -I"C:/GP2XSDK/include"  -I"C:/devkitGP2X/include"  -I"D:/Downloads/GP2X/fm-0.99/fm-0.99" 
CXXINCS =  -I"C:/GP2XSDK/include/GP2X"  -I"C:/GP2XSDK/include/SDL"  -I"C:/GP2XSDK/lib/gcc/mingw32/3.4.2/include"  -I"C:/GP2XSDK/include/c++/3.4.2/backward"  -I"C:/GP2XSDK/include/c++/3.4.2/mingw32"  -I"C:/GP2XSDK/include/c++/3.4.2"  -I"C:/GP2XSDK/include"  -I"D:/Downloads/GP2X/fm-0.99/fm-0.99" 
BIN  = fm.exe
CXXFLAGS = $(CXXINCS)   -DWIN32
CFLAGS = $(INCS) -D_REENTRANT   -DWIN32
RM = rm -f
MKDIR = cygwin-mkdir -p

.PHONY: all all-before all-after clean clean-custom

all: all-before fm.exe all-after

all-before:
	$(MKDIR) "win"


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $@ $(LIBS)

win/misc.o: misc.c
	$(CPP) -c misc.c -o win/misc.o $(CXXFLAGS)

win/drv_linux.o: drv_linux.c
	$(CPP) -c drv_linux.c -o win/drv_linux.o $(CXXFLAGS)

win/eos.o: eos.c
	$(CPP) -c eos.c -o win/eos.o $(CXXFLAGS)

win/fm.o: fm.c
	$(CPP) -c fm.c -o win/fm.o $(CXXFLAGS)

win/font.o: font.c
	$(CPP) -c font.c -o win/font.o $(CXXFLAGS)

win/init.o: init.c
	$(CPP) -c init.c -o win/init.o $(CXXFLAGS)

win/io.o: io.c
	$(CPP) -c io.c -o win/io.o $(CXXFLAGS)

win/main.o: main.c
	$(CPP) -c main.c -o win/main.o $(CXXFLAGS)

win/match.o: match.c
	$(CPP) -c match.c -o win/match.o $(CXXFLAGS)

win/matchday.o: matchday.c
	$(CPP) -c matchday.c -o win/matchday.o $(CXXFLAGS)

win/menu.o: menu.c
	$(CPP) -c menu.c -o win/menu.o $(CXXFLAGS)
